pimcore:
    objects:
        custom_layouts:
            definitions:
                9cfe132d-0b1e-4f4f-98a2-daa6ca30a1d8:
                    id: 9cfe132d-0b1e-4f4f-98a2-daa6ca30a1d8
                    name: retreat
                    description: ''
                    creationDate: 1696846508
                    modificationDate: 1696846515
                    userOwner: 2
                    classId: incident
                    layoutDefinitions:
                        name: pimcore_root
                        type: null
                        region: null
                        title: null
                        width: 0
                        height: 0
                        collapsible: false
                        collapsed: false
                        bodyStyle: null
                        datatype: layout
                        children:
                            -
                                name: Layout
                                type: null
                                region: null
                                title: ''
                                width: ''
                                height: ''
                                collapsible: false
                                collapsed: false
                                bodyStyle: ''
                                datatype: layout
                                children:
                                    -
                                        name: incidentdate
                                        title: Incidentdate
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: true
                                        style: ''
                                        permissions: null
                                        fieldtype: date
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        defaultValue: null
                                        useCurrentDate: false
                                        columnType: bigint(20)
                                        defaultValueGenerator: ''
                                        datatype: data
                                    -
                                        name: description
                                        title: Description
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: true
                                        style: ''
                                        permissions: null
                                        fieldtype: textarea
                                        relationType: false
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        maxLength: null
                                        showCharCount: false
                                        excludeFromSearchIndex: false
                                        height: ''
                                        width: ''
                                        datatype: data
                                    -
                                        name: placeid
                                        title: Placeid
                                        tooltip: ''
                                        mandatory: false
                                        noteditable: false
                                        index: false
                                        locked: true
                                        style: ''
                                        permissions: null
                                        fieldtype: manyToOneRelation
                                        relationType: true
                                        invisible: false
                                        visibleGridView: false
                                        visibleSearch: false
                                        classes:
                                            -
                                                classes: Location
                                        displayMode: grid
                                        pathFormatterClass: ''
                                        assetInlineDownloadAllowed: false
                                        assetUploadPath: ''
                                        allowToClearRelation: true
                                        objectsAllowed: true
                                        assetsAllowed: false
                                        assetTypes: {  }
                                        documentsAllowed: false
                                        documentTypes: {  }
                                        width: ''
                                        datatype: data
                                locked: false
                                fieldtype: panel
                                layout: null
                                border: false
                                icon: ''
                                labelWidth: 100
                                labelAlign: left
                        locked: false
                        fieldtype: panel
                        layout: null
                        border: false
                        icon: null
                        labelWidth: 100
                        labelAlign: left
                    default: 0
