pimcore:
    documents:
        doc_types:
            definitions:
                641be4cd-7866-4b50-801e-1750f585475a:
                    name: Contact-Page
                    group: ''
                    controller: 'App\Controller\ContentController::ContactAction'
                    template: null
                    type: page
                    priority: 0
                    creationDate: 1695985072
                    modificationDate: 1695985426
                    staticGeneratorEnabled: false
